"""Stage task templates. Entering a stage generates its tasks."""

from __future__ import annotations

TASK_TEMPLATES: dict[str, list[str]] = {
    "REQUIREMENT": ["CASE_REQUIREMENT_CONFIRMATION"],
    "PROPERTY_SEARCH": ["PROPERTY_SEARCH"],
    "PROPERTY_APPROVAL": ["PROPERTY_APPROVAL"],
    "SECURITY_DEPOSIT": ["SD_PAYMENT"],
    "LOA": ["LOA_PREPARATION"],
    "AGREEMENT": ["AGREEMENT_EXECUTION"],
    "QUOTATION": ["QUOTATION_COLLECTION"],
    "ACCOUNTS": ["ACCOUNTS_REVIEW"],
    "CC_APPROVAL": ["CC_APPROVAL"],
    "MD_APPROVAL": ["MD_APPROVAL"],
    "PAYMENT": ["PO_PREPARATION", "PAYMENT_EXECUTION"],
    "INFRASTRUCTURE": ["INFRASTRUCTURE_WORK"],
    "OPERATIONAL_READINESS": ["READINESS_CHECK"],
    "OPENING": ["OPENING_EXECUTION"],
    "COMPLETED": [],
}